# -*- coding: utf-8 -*-
"""Clalci

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LG5UAHF2jhf9CCJMhck0udV6YSoKm817
"""



print("Simple Calculator") #Use of print statement x = 10 #Integer data type can be changed
y = int(input("Enter your value: "))#20 #Integer data type can be changed
x=int(input("Enter your value: "))
sum = x + y #Sum of x and y
difference = x - y #Difference of x and y product = x * y #Product of x and y quotient = x/y #Quotient of x by y
product=x*y
quotient=x/y
remainder = x % y #Remainder of x by y
print("The sum of x and y is ", sum) #Printing the sum
print("The difference between x and y is ", difference) #Printing the difference
print("The product of x and y is ",product)
print("The quotient of x by y is ", quotient) #Printing the Quotient



